// 부산 워케이션 거점, 워크스페이스, 로컬 F&B/체험 파트너십 마스터 데이터

import { LocationPoint, Workspace, PartnerBenefit, TimeAttackCourse } from '@/types';

// 부산 주요 워케이션 거점 지역
export const BUSAN_HUBS: LocationPoint[] = [
  {
    id: 'hub-yeongdo',
    name: '영도 (봉래·청학·흰여울)',
    lat: 35.0912,
    lng: 129.0435,
    address: '부산광역시 영도구 봉래동',
    area: '영도',
  },
  {
    id: 'hub-choryang',
    name: '부산역·초량 (원도심·이바구길)',
    lat: 35.1152,
    lng: 129.0422,
    address: '부산광역시 동구 중앙대로 206',
    area: '초량/동구',
  },
  {
    id: 'hub-nampo',
    name: '남포·자갈치 (중구 문화특구)',
    lat: 35.0984,
    lng: 129.0305,
    address: '부산광역시 중구 남포동',
    area: '남포/중구',
  },
  {
    id: 'hub-gwangan',
    name: '광안리 (해변·민락)',
    lat: 35.1532,
    lng: 129.1189,
    address: '부산광역시 수영구 광안해변로',
    area: '광안리',
  },
  {
    id: 'hub-haeundae',
    name: '해운대 (센텀·구남로)',
    lat: 35.1587,
    lng: 129.1603,
    address: '부산광역시 해운대구 해운대해변로',
    area: '해운대',
  },
];

// 부산 워크스페이스 (카페 & 공유오피스) 마스터
export const INITIAL_WORKSPACES: Workspace[] = [
  {
    id: 'ws-1',
    name: '부산 워케이션 거점센터 (아스티호텔 24F)',
    category: '공공워케이션센터',
    lat: 35.1158,
    lng: 129.0416,
    address: '부산광역시 동구 중앙대로 214번길 7-8 아스티호텔 24층',
    area: '초량/동구',
    features: {
      hasOutlet: true,
      hasWifi: true,
      isQuiet: true,
      hasOceanView: true,
    },
    openHours: '09:00 ~ 20:00 (주말 휴무)',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    rating: 4.9,
    reviewCount: 142,
    description: '부산시 공식 워케이션 거점 센터. 부산항 파노라마 오션뷰와 1인 포커스룸, 회의실 완비.',
  },
  {
    id: 'ws-2',
    name: '블루포트 2021 (영도 청학동)',
    category: '공유오피스',
    lat: 35.0935,
    lng: 129.0558,
    address: '부산광역시 영도구 대교로46번길 24',
    area: '영도',
    features: {
      hasOutlet: true,
      hasWifi: true,
      isQuiet: true,
      hasOceanView: true,
    },
    openHours: '08:00 ~ 22:00',
    imageUrl: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800&q=80',
    rating: 4.8,
    reviewCount: 98,
    description: '부산대교와 선박 부두가 내려다보이는 로컬 크리에이터 코워킹 라운지.',
  },
  {
    id: 'ws-3',
    name: '모모스 로스터리 & 커피바 영도',
    category: '작업카페',
    lat: 35.0901,
    lng: 129.0402,
    address: '부산광역시 영도구 봉래나루로 160',
    area: '영도',
    features: {
      hasOutlet: true,
      hasWifi: true,
      isQuiet: false,
      hasOceanView: true,
    },
    openHours: '09:00 ~ 18:30',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80',
    rating: 4.9,
    reviewCount: 312,
    description: '월드 바리스타 챔피언십 우승의 명성. 바다 바로 앞 대형 로스터리 작업 명소.',
  },
  {
    id: 'ws-4',
    name: '노티스 (Notice 1950 쌀창고 카페)',
    category: '작업카페',
    lat: 35.1098,
    lng: 129.0375,
    address: '부산광역시 중구 대교로 135',
    area: '남포/중구',
    features: {
      hasOutlet: true,
      hasWifi: true,
      isQuiet: true,
      hasOceanView: false,
    },
    openHours: '11:00 ~ 21:00',
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80',
    rating: 4.7,
    reviewCount: 86,
    description: '1950년 건립된 항구 쌀창고를 재생한 감성 복합문화공간. 넓은 테이블과 콘센트 좌석.',
  },
  {
    id: 'ws-5',
    name: '밀락더마켓 워크라운지',
    category: '호텔라운지',
    lat: 35.1545,
    lng: 129.1301,
    address: '부산광역시 수영구 민락수변로17번길 56',
    area: '광안리',
    features: {
      hasOutlet: true,
      hasWifi: true,
      isQuiet: false,
      hasOceanView: true,
    },
    openHours: '10:00 ~ 24:00',
    imageUrl: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=800&q=80',
    rating: 4.8,
    reviewCount: 230,
    description: '광안대교 오션뷰가 계단식 스탠드에 펼쳐지는 랜드마크. 퇴근 직후 F&B 즐기기 최적.',
  },
  {
    id: 'ws-6',
    name: '스파크플러스 센텀시티점',
    category: '공유오피스',
    lat: 35.1702,
    lng: 129.1298,
    address: '부산광역시 해운대구 센텀중앙로 78',
    area: '해운대',
    features: {
      hasOutlet: true,
      hasWifi: true,
      isQuiet: true,
      hasOceanView: false,
    },
    openHours: '24시간 운영',
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&q=80',
    rating: 4.8,
    reviewCount: 75,
    description: '센텀 IT 밸리의 프리미엄 공유오피스. 듀얼 모니터 및 폰부스 지원.',
  },
];

// 부산 체험 & 로컬 F&B 파트너십 마케팅 기업 및 모바일 할인권
export const PARTNER_BENEFITS: PartnerBenefit[] = [
  {
    id: 'benefit-1',
    businessName: '삼진어묵 영도본점 & 어묵베이커리',
    category: 'F&B',
    title: '어묵베이커리 15% 즉시 할인권',
    discountRate: '15% OFF',
    couponCode: 'OFFCE-SAMJIN-15',
    validUntil: '2026-12-31',
    description: '1953년부터 시작된 대한민국 최초의 어묵 제조사. 시그니처 어묵고로케와 치즈어묵바를 할인된 가격에 즐기세요.',
    address: '부산 영도구 태종로99번길 36',
    imageUrl: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=800&q=80',
    targetSpotId: 'spot-samjin',
  },
  {
    id: 'benefit-2',
    businessName: '초량1941 (적산가옥 바닐라우유 카페)',
    category: 'F&B',
    title: '수제 우유 주문 시 드립백 1팩 무료 증정',
    discountRate: '무료 증정',
    couponCode: 'OFFCE-CHORYANG-GIFT',
    validUntil: '2026-12-31',
    description: '1941년 건립된 일본식 목조가옥을 개조한 숲속 힐링 카페. 바닐라우유와 말차우유가 유명합니다.',
    address: '부산 동구 망양로 533-5',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80',
    targetSpotId: 'spot-choryang1941',
  },
  {
    id: 'benefit-3',
    businessName: '흰여울 원데이 바다비누 공방 (소소아트)',
    category: '체험/액티비티',
    title: '부산 바다비누 만들기 체험 클래스 20% 할인',
    discountRate: '20% OFF',
    couponCode: 'OFFCE-OCEAN-SOAP20',
    validUntil: '2026-12-31',
    description: '흰여울문화마을 절벽 위에서 영도 앞바다의 노을빛을 담은 친환경 수제 바다 비누를 직접 제작해보는 이색 체험.',
    address: '부산 영도구 절영로 210',
    imageUrl: 'https://images.unsplash.com/photo-1607006314180-34830e014545?w=800&q=80',
    targetSpotId: 'spot-huinnyeoul',
  },
  {
    id: 'benefit-4',
    businessName: '부평 깡통야시장 로컬맥주 펍 (남포비어)',
    category: 'F&B',
    title: '안주 주문 시 부산 수제 에일맥주(350ml) 1잔 무료',
    discountRate: '1잔 무료',
    couponCode: 'OFFCE-NAMPO-BEER',
    validUntil: '2026-12-31',
    description: '자갈치와 깡통시장의 활기가 넘치는 원도심 펍. 퇴근 후 부산의 맛있는 로컬 안주와 시원한 맥주 한 잔!',
    address: '부산 중구 부평1길 48',
    imageUrl: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&q=80',
    targetSpotId: 'spot-bupyeong',
  },
  {
    id: 'benefit-5',
    businessName: '광안리 선셋 요트투어 (요트탈래)',
    category: '체험/액티비티',
    title: '퇴근 후 선셋 & 야경 요트투어 30% 즉시 할인',
    discountRate: '30% OFF',
    couponCode: 'OFFCE-YACHT-30',
    validUntil: '2026-12-31',
    description: '오후 6시 30분 골든아워 출항! 광안대교 아래에서 노을과 야경 불꽃놀이를 감상하는 로맨틱 퇴근 코스.',
    address: '부산 해운대구 해운대해변로 84 수영만요트경기장',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    targetSpotId: 'spot-gwangan-yacht',
  },
];

// 1시간 타임어택 추천 기본 코스 (원도심 영도/초량 중심)
export const SEED_COURSES: TimeAttackCourse[] = [
  {
    id: 'course-yeongdo-sunset',
    title: '영도 해안절벽 노을 & 어묵 피크닉 1시간 코스',
    theme: '노을산책',
    estimatedMinutes: 58,
    totalDistanceKm: 3.6,
    partnerBenefit: PARTNER_BENEFITS[0], // 삼진어묵 15% 할인 연계
    spots: [
      {
        step: 1,
        role: '맛집',
        spot: {
          contentid: 'spot-samjin',
          contenttypeid: '39',
          title: '삼진어묵 영도본점 & 베이커리',
          addr1: '부산광역시 영도구 태종로99번길 36',
          mapx: 129.0405,
          mapy: 35.0935,
          tel: '051-412-5468',
          firstimage: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=800&q=80',
          categoryLabel: '로컬 F&B / 베이커리',
          overview: '퇴근 후 출출한 배를 달래는 갓 튀긴 치즈고로케와 로컬 푸드. 제휴 할인권 적용 가능.',
          partnerBenefit: PARTNER_BENEFITS[0],
        },
      },
      {
        step: 2,
        role: '산책/문화',
        spot: {
          contentid: 'spot-huinnyeoul',
          contenttypeid: '12',
          title: '흰여울문화마을 & 절영해안산책로',
          addr1: '부산광역시 영도구 절영로 194',
          mapx: 129.0468,
          mapy: 35.0772,
          tel: '051-419-4041',
          firstimage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
          categoryLabel: '해안 산책로 / 일몰 명소',
          overview: '바다 바로 위 절벽 마을을 따라 걷는 일몰의 성지. 노을빛 남항 바다를 조망하며 힐링.',
          partnerBenefit: PARTNER_BENEFITS[2],
        },
      },
      {
        step: 3,
        role: '숙소',
        spot: {
          contentid: 'spot-stay-yeongdo',
          contenttypeid: '32',
          title: '라발스 호텔 부산 (오션뷰 테라스)',
          addr1: '부산광역시 영도구 봉래나루로 82',
          mapx: 129.0392,
          mapy: 35.0945,
          tel: '051-790-1500',
          firstimage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
          categoryLabel: '워케이션 감성 숙소',
          overview: '영도대교와 부산항이 한눈에 보이는 최적의 워케이션 숙소. 도보 5분 거리 접근성.',
        },
      },
    ],
  },
  {
    id: 'course-choryang-ibagu',
    title: '원도심 이바구길 산복도로 야경 1시간 코스',
    theme: '야경감성',
    estimatedMinutes: 55,
    totalDistanceKm: 3.2,
    partnerBenefit: PARTNER_BENEFITS[1], // 초량1941 연계
    spots: [
      {
        step: 1,
        role: '맛집',
        spot: {
          contentid: 'spot-choryang1941',
          contenttypeid: '39',
          title: '초량 1941 & 초량 불백거리',
          addr1: '부산광역시 동구 망양로 533-5',
          mapx: 129.0372,
          mapy: 35.1189,
          tel: '051-462-7774',
          firstimage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80',
          categoryLabel: '로컬 미식 / 감성 카페',
          overview: '부산의 명물 초량 불백 식사 후, 고즈넉한 적산가옥 카페에서 마시는 시원한 바닐라 우유.',
          partnerBenefit: PARTNER_BENEFITS[1],
        },
      },
      {
        step: 2,
        role: '산책/문화',
        spot: {
          contentid: 'spot-ibagu-monorail',
          contenttypeid: '12',
          title: '168계단 모노레일 & 유치환의 우체통',
          addr1: '부산광역시 동구 영초위길 22',
          mapx: 129.0354,
          mapy: 35.1147,
          tel: '051-440-4061',
          firstimage: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=800&q=80',
          categoryLabel: '산복도로 야경 명소',
          overview: '부산항 대교와 원도심의 반짝이는 불빛이 한눈에 내려다보이는 감성 야경 핫스팟.',
        },
      },
      {
        step: 3,
        role: '숙소',
        spot: {
          contentid: 'spot-asti-hotel',
          contenttypeid: '32',
          title: '아스티 호텔 부산역',
          addr1: '부산광역시 동구 중앙대로 214번길 7-8',
          mapx: 129.0416,
          mapy: 35.1158,
          tel: '051-409-8888',
          firstimage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
          categoryLabel: '비즈니스 & 워케이션 호텔',
          overview: '부산역 바로 앞. 워케이션 거점센터 24층과 직결되어 일과 쉼이 한곳에서 완성.',
        },
      },
    ],
  },
  {
    id: 'course-rainy-culture',
    title: '비 오는 날엔 감성 충전 실내 문화 코스',
    theme: '실내힐링',
    estimatedMinutes: 20,
    totalDistanceKm: 1.2,
    partnerBenefit: PARTNER_BENEFITS[3], // 남포비어 연계
    spots: [
      {
        step: 1,
        role: '맛집',
        spot: {
          contentid: 'spot-bupyeong',
          contenttypeid: '39',
          title: '남포 비어 & 부평 깡통야시장 F&B',
          addr1: '부산 중구 부평1길 48',
          mapx: 129.0255,
          mapy: 35.1012,
          tel: '051-241-1120',
          firstimage: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&q=80',
          categoryLabel: '비 오는 날의 로컬 펍',
          overview: '빗소리와 함께 즐기는 바삭한 빈대떡과 시원한 부산 로컬 에일 맥주 한 잔.',
          partnerBenefit: PARTNER_BENEFITS[3],
        },
      },
      {
        step: 2,
        role: '산책/문화',
        spot: {
          contentid: 'spot-bosu-book',
          contenttypeid: '14',
          title: '보수동 책방골목 문화관 & 아테네학당',
          addr1: '부산광역시 중구 대청로 67번길 5',
          mapx: 129.0268,
          mapy: 35.1042,
          tel: '051-743-7650',
          firstimage: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&q=80',
          categoryLabel: '실내 문화시설 / 전시관',
          overview: '한국전쟁 피난 시절부터 이어진 헌책방 골목의 레트로 감성과 북카페 전시.',
        },
      },
      {
        step: 3,
        role: '숙소',
        spot: {
          contentid: 'spot-nampo-stay',
          contenttypeid: '32',
          title: '하운드 호텔 남포 프리미어',
          addr1: '부산광역시 중구 보수대로 24',
          mapx: 129.0285,
          mapy: 35.1018,
          tel: '051-242-0000',
          firstimage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80',
          categoryLabel: '부티크 디자인 호텔',
          overview: '원도심 문화거리와 자갈치를 걸어서 누비는 편안한 부티크 힐링 스테이.',
        },
      },
    ],
  },
];
